### PR TITLE
Added "Commit & Push" functionality

### PR DESCRIPTION
**Pull request by brusch**

### CODE REVIEW

**Comment by mathieudutour** [comment]
I'm a bit worried about adding to many combinations of commands, it mights be overwhelming for new users. 
But I agree that it's a nice shortcut for power users.

How about not showing it on the menu but still adding the shortcut?

**Comment by brusch** [comment]
That's an understandable point ... :) The problem is that nobody will recognize this functionality if there isn't an item for this somewhere in the menu. 
Another solution would be to add another checkbox to the commit dialog, where you can choose to push after commit. 

What do you think?

**Comment by mathieudutour** [comment]
I like the checkbox.

What I would to do also is to create an "settings" view where you could decide whether the different checkboxes should be ticked by default or not and solve #22

**Comment by brusch** [comment]
Makes sense. I'll try to make the changes as soon as possible and will update this PR. 
Thanks!

**Comment by mathieudutour** [comment]
I added the settings view, should be easy to add another checkbox with a preference

**Comment by mathieudutour** [comment]
Any chance that you will have time to work on that or should I do it?

**Comment by brusch** [comment]
The next few weeks I'm pretty busy, but afterwards i should be able to do it.

**Comment by mathieudutour** [comment]
I'm going to close this because it's super old and conflicting with everything

**Pull request closed without merging**
