### PR TITLE
new sync to JSON which allow merging

### PR DESCRIPTION
**Pull request by mathieudutour**
[Git.sketchplugin.zip](https://github.com/mathieudutour/git-sketch-plugin/files/737576/Git.sketchplugin.zip)

### CODE REVIEW

**Comment by jdsimcoe** [comment]
@mathieudutour I am very curious about this JSON sync and your new plugin: https://github.com/mathieudutour/sketch-module-json-sync. I've been beta-testing [Abstract](https://www.abstractapp.com/) and they have very granular commit and merge features. I've also heard rumor from someone on the Figma team that Sketch is moving to a JSON document format. Anyway, I would love to know what this new JSON functionality entails.

**Comment by mathieudutour** [comment]
Yes I'm also beta-testing Abstract. It's great at hiding the complexity of git but on the other hand, it's trying to replace GiHub which is a shame because I believe there is a potential to close the bridge between devs and designers around version control.

> I've also heard rumor from someone on the Figma team that Sketch is moving to a JSON document format

That's what Ale have implied here: http://sketchplugins.com/d/4-introductions/15 but who knows ;)

Anyway, I wanted to try to create something a bit like Abstract but based on raw git and Sketch-first (as opposed to needing to open Abstract first to work on your sketch file)

I might post a screencast later today if I have time.

(https://github.com/mathieudutour/sketch-module-json-sync is not a plugin, it's what I call a sketch-module which is basically a npm package that you can use in your plugin. cf. https://github.com/mathieudutour/skpm)

**Comment by mathieudutour** [comment]
Btw, if anybody have a sketch file showing every possible feature/style, I'd be interested

**Comment by jdsimcoe** [comment]
@mathieudutour 👍 Brilliant!

**Comment by mathieudutour** [comment]
Sketch 43 (http://sketchplugins.com/d/87-new-file-format-in-sketch-43/28) changes everything.

I'll scrap all of that and start from scratch. It should be a lot simpler and more reliable :tada:

**Pull request closed without merging**
