### PR TITLE
only execute the  `exportArtboards` function in git repository

### PR DESCRIPTION
**Pull request by yuchuanxi**
when `exportArtboards`, the faild alert will be show, 
but actully, the export action has done!

image

### CODE REVIEW

**Comment by mathieudutour** [comment]
oh interesting. 

I think we can do something even better: we can still execute the `export artboards` function, the only thing that fails is `git add` here: https://github.com/mathieudutour/git-sketch-plugin/blob/master/Git.sketchplugin/exportArtboard.sh#L82-L87. 

we can check if we are in a git repo there and only do `git add` if we are.

**Comment by yuchuanxi** [comment]
Q1: whether need to export artboards out of git repo
Q2: if need, can we export to `exportedArtbords` or `fileNameArtboards`, not `.exportedArtbords`
Q3: #123 whether we need  limit export in git repo
Q4: if no need,  add option to limit？

**Comment by mathieudutour** [comment]
> whether need to export artboards out of git repo

hum, valid point. It's true that I don't see any use case for it. So I'm going to merge this PR but I'll wait for your next PR about auto-exporting artboards before doing a release.

> can we export to `exportedArtbords` or `fileNameArtboards`, not `.exportedArtbords`

there is already an option to change the folder name

Thanks a lot for your work!

**Comment by yuchuanxi** [comment]
the PR will be soon

**Pull request merged**
