### PR TITLE
pretty diffs example

### PR DESCRIPTION
**Pull request by mathieudutour**

### CODE REVIEW

**Comment by gaharrington** [comment]
What tool/software do I use to see the side-by-side before/after like you are showing here?

**Comment by mathieudutour** [comment]
this plugin? I'm not sure what you are asking

**Comment by gaharrington** [comment]
I thought this thread would give you some context...sorry if my question was confusing!

I am referring to the example on this page:
https://mathieudutour.github.io/git-sketch-plugin/

And, specifically, this screenshot:
https://raw.githubusercontent.com/mathieudutour/git-sketch-plugin/master/example/ScreenShotNice.png

What software are you using in that screenshot?

**Comment by mathieudutour** [comment]
just click on "Files changed" at the top of the first comment of this thread. It's the UI of github.

**Comment by gaharrington** [comment]
Ahhh....thank you for clarifying.

I am looking for MacOS native app that has a similar before/after view. From the cropped screenshot, I thought I was looking at a MacOS window. 

Thank you for the clarification.

**Pull request merged**
